### ISSUE TITLE
Compatibility with babel ?

### ISSUE THREAD

**Issue by crubier** [facebook-atom/atom-ide-debugger-node#1]
Hi, very nice package, this is amazing. It would be so nice if this could support babel though ! Any plans for this ?

**Comment by mostafaeweda** [comment]
The node debugger already has source map options (see the `Out Files` field)
<img width="1187" alt="screenshot 2018-04-18 14 24 31" src="https://user-images.githubusercontent.com/264320/38959127-44019fc0-4314-11e8-83ee-d734669078fb.png">
That'd map to the underlying VSCode's node debugger source map option: `outFiles`: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps

To debug any babel-transpiled source code - https://babeljs.io/docs/usage/cli/#compile-with-source-maps - you can either:
* Transpile with inline source maps (I prefer this option).
* Compile to an out directory & set the `Out Files` field path in the UI.
