### ISSUE TITLE
running with nuxt.js

### ISSUE THREAD

**Issue by cloudbluedigital** [facebook-atom/atom-ide-debugger-node#2]
Hi guys,

I am trying to set the debugger for nuxt.js library

![untitled](https://user-images.githubusercontent.com/22678404/39250313-72967b88-4898-11e8-93a7-1ebd7f22df1d.jpg)

This is what I get and my config is:

![untitled2](https://user-images.githubusercontent.com/22678404/39250334-7e0eb53e-4898-11e8-8f82-0f83119c2f26.jpg)

if I change cwd to C:\Coding\website_nuxt <without .nuxt> it get's to a point where it's compiling and I get
```
Failed to start debugger process: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).
```

**Comment by cloudbluedigital** [comment]
changed dev argument to dev-debug and set it in package.json `"dev-debug": "node --inspect=9229 node_modules/nuxt/bin/nuxt"` it still times-out. in debugger it runs `C:\Program Files (x86)\Yarn\bin\yarn.cmd --inspect=25360 --debug-brk node_modules\nuxt\bin\nuxt dev-debug` which is fine except the part that --inspect=25360 and it's running on port 9229 that's why I get the error that it cannot connect to runtime process. is there possibility to get rid of it

**Comment by mostafaeweda** [comment]
Can you try running the command outside & attach to the port from Nuclide instead?
In your screenshot, I can see the environment variables input format is wrong.
Instead, you'd want: `NODE_ENV=development DEBUG=nux` - I'm improving these fields' documentation in the next version.

I assume the debugger works for simple scripts - if so, then it must be a configuration issue?
I haven't really tested on windows nor folders with spaces.
